### ISSUE TITLE
Start developing Unity!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by SiamSami** [unity8-team/unity8#1]
Please and I mean please start developing Unity desktop again!!!!!!!!!!!!!!!!!!!!

THIS IS NOT A JOKE!!! I just really love the Unity desktop environment!!!!

SO PLEASE AND PLEASE START DEVELOPING UNITY AGAIN!!!!!!!!!!!!!!!!!!

**Comment by AlanGriffiths** [comment]
@SiamSami I think you are requesting this in the wrong place: unity8-team are people that _used to be_ employed by Canonical to work on convergence.

You probably mean Unity7: for recent progress with that see: https://community.ubuntu.com/c/desktop/ubuntu-unity-dev

Unity8 never got past the "preview" stage on desktop. Canonical stopped that work almost a year ago and disbanded the team (most of whom lost their jobs).

The convergence work represented by the unity8-team repos was "free" software (GPL/LGPL) which means the convergence work could (and has) been continued at: https://ubports.com/.

**Comment by thedonquixotic** [comment]
Just wanted to say that I'm a new Ubuntu user and while I don't know the full extent of how Unity 8 works, I think it looks fucking rad from the preview pictures, and I'm going to try it out. I don't totally understand why there was backlash against it?
